apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: shop-cron-scaler
  namespace: aws9e
spec:
  scaleTargetRef:
    name: shop
  pollingInterval: 30
  cooldownPeriod: 300
  minReplicaCount: 1       # 기본 최소는 1개
  maxReplicaCount: 10
  triggers:
    # 근무시간 스케일업: 9시~18시 사이에 desiredReplicas 3개로 유지
    - type: cron
      metadata:
        timezone: "Asia/Seoul"
        start: "0 9 * * *"         # 오전 9시 정각
        end: "0 18 * * *"          # 오후 6시 정각
        desiredReplicas: "3"

    # 근무시간 외 스케일다운: 18시~다음날 9시까지 1개로
    - type: cron
      metadata:
        timezone: "Asia/Seoul"
        start: "0 18 * * *"        # 오후 6시 정각
        end: "0 9 * * *"           # 다음날 9시 정각
        desiredReplicas: "1"

    # CPU 기준으로 60% 이상이면 확장
    - type: cpu
      metadata:
        type: Utilization
        value: "60"
