apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-deploy
  namespace: aws9e
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop
  template:
    metadata:
      labels:
        app: shop
    spec:
      containers:
      - name: shopctn
        image: nginx
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "200m"
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: shop-volume
      volumes:
      - name: shop-volume
        persistentVolumeClaim:
          claimName: shop-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: shop-svc
  namespace: aws9e
spec:
  selector:
    app: shop
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shop-pvc
  namespace: aws9e
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: aws9e-nfs-sc